question_data = [
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first computer bug was formed by faulty wires.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "DHCP stands for Dynamic Host Configuration Port.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]

